### ISSUE TITLE
LuaJIT

### ISSUE THREAD

**Issue by concatime** [jmmv/lutok#3] opened 2017-11-25 23:53 UTC
Is it possible to use LuaJIT? If so, how?

**Comment by jmmv** [comment] 2017-11-26 02:58
I don't know what LuaJIT is and can't tell what you mean by "use LuaJIT" in this context... but I suspect the answer is no.

Regardless, this is not a bug report... so closing.

**Closed by jmmv** 2017-11-26 02:58 UTC
